name: CI

on:
    push: 
        # branches: [master]
    pull_request:
        # branches: [master]
jobs:
    testing:
        name: Test App
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                fetch-depth: 0
            - name: Just a test msg
              run: echo "test case"
            - name: Setup node
              uses: actions/setup-node@v3
              with:
                node-version: '18.x'
            - name: Install packages
              run: npm ci
            - name: Unit testing
              run: CI=true npm test
            - name: Install browsers
              run: npx playwright install
            - name: E2E testing
              run: npx playwright test --quiet --project=chromium --reporter=list