name: Tag release

on: 
    push:
        tags:
            - '*'

jobs:
  create_issue:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .
    permissions:
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: Install packages
        run: npm ci
      - name: Unit testing
        run: CI=true npm test |& tee -a ./ci/report.txt
      - name: Install browsers
        run: npx playwright install
      - name: E2E testing
        run: npx playwright test --quiet --project=chromium --reporter=list |& tee -a ./ci/report.txt
      - name: run ci file
        if: ${{ always() }}
        id: create-issue
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          GH_ACTOR: ${{ github.actor }}
          GH_REF_NAME: ${{ github.ref_name }}
          GH_SHA: ${{ github.sha }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: node ./ci/createIssue.js
      - name: create-release-branch
        if: ${{ success() }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          GH_ACTOR: ${{ github.actor }}
          GH_REF_NAME: ${{ github.ref_name }}
          GH_SHA: ${{ github.sha }}
        run: node ./ci/createBranch.js

      