name: Tag release

on: 
    push:
        tags:
            - '*'
permissions:
    contents: read
    issues: write 
jobs:
    issue:
        name: Create Issue
        runs-on: ubuntu-latest
        steps:
           - name: create issue for logging new release
             uses: actions/checkout@v3
             uses: JasonEtco/create-an-issue@v2
             env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}